### ISSUE TITLE
Expected release date

### ISSUE THREAD

**Issue by misraya** [SysCV/cascade-detr#1]
Hi, 

I recently read your paper and really enjoyed it, congratulations on the ICCV acceptance. Could you provide an update on the expected release date for the code and checkpoints associated with the paper?

Best regards,
Misra

**Comment by ymq2017** [comment]
Hi, thanks for watching our work! We will release it at the beginning of September after being well-prepared.

**Comment by ymq2017** [comment]
Hi, the code of cascade_dn_detr is released now. :)
